core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientInterfaceSpec.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedBackupClientInterface.scala, core/src/main/scala/io/aiven/guardian/kafka/Errors.scala, core/src/test/scala/io/aiven/guardian/akka/AkkaStreamTestKit.scala, core/src/test/scala/io/aiven/guardian/kafka/Utils.scala
This PR fixes the prevalent issues regarding fencepost cases in regards to the streaming algorithm. The PR should fix most (highly likely all) problems identified with https://github.com/aiven/guardian-for-apache-kafka/pull/75 .
The PR also fixes regressions that occurred in tests (which meant that the mock tests weren't actually testing anything properly) and also adds additional tests including one that critically makes sure that termination of JSON works correctly which is import for the restore part of the tool.
There are multiple issues that this PR addresses, one of the reasons why the PR is non trivial in size is that initially the intention was to fix the issue with tests being broken which when resolved revealed other problems, a summation is provided here
* The initial reason …
=> Fix fencepost issues with stream algorithm plus fix tests

backup-gcs/src/main/scala/io/aiven/guardian/kafka/backup/gcs/BackupClient.scala, backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/BackupClientChunkState.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/KafkaClientWithKillSwitch.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/MockedS3BackupClientInterface.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala, core-backup/src/main/resources/reference.conf, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/KafkaClient.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/KafkaClientInterface.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/configs/Backup.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/ConfigSpec.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedBackupClientInterface.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedKafkaClientInterface.scala, core-s3/src/main/resources/reference.conf, core-s3/src/main/scala/io/aiven/guardian/kafka/s3/configs/S3.scala, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/Generators.scala
This PR restructures some of the components in Guardian so that the dependencies are minimized. This is mainly a result of working on https://github.com/aiven/guardian-for-apache-kafka/pull/83, as it turns there are configurations/components which are mandatory that shouldn't be, or are in the wrong module.
Regarding the cli feature, without this PR we run into the problem where we are forced to write configurations which dont make sense (i.e. `compaction-bucket` for backup) or in other cases we there is no configuration for options we do need to provide (i.e. `group-id`)
The PR is split into 3 commits, each complaining the reasoning behind the change
* `Move KafkaClient into core-backup`: `KafkaClient` is a KafkaConsumer that listens to a Kafka cluster, strictly speaking this …
=> Restructure kafka client into backup

backup-gcs/src/main/scala/io/aiven/guardian/kafka/backup/gcs/BackupClient.scala, backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedBackupClientInterface.scala
This PR fixes the suspend/resume handling for the `FirstFromPeriod` case. As documented for the `Backup` configuration section in `TimeConfiguration`, when using `FirstFromPeriod` if you kill a backup and then resume it, it will create a new object regardless of what the current configured `duration` is as long as at least one chunk has been persisted into S3.
The current behavior of Guardian does not do this, the PR fixes this.
In addition the PR also renames some tests so its much more clear what is actually being tested
The intention of this PR is to keep the interface for `BackupClientInterface` as simple as possible so that implementations of `BackupClientInterface` (i.e. S3's `BackupClient`) are trivial, simple and easy to understand even at a cost of internals of …
=> Fix handling for suspend/resume case for PeriodFromFirst

build.sbt, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/App.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupApp.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/Main.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/S3App.scala, cli-backup/src/test/scala/io/aiven/guardian/kafka/CliSpec.scala, core-cli/src/main/resources/application.conf, core-cli/src/main/resources/logback.xml, core-cli/src/main/scala/io/aiven/guardian/cli/AkkaSettings.scala, core-cli/src/main/scala/io/aiven/guardian/cli/arguments/StorageOpt.scala, core-cli/src/main/scala/io/aiven/guardian/cli/options/Options.scala, core/src/main/resources/reference.conf
This change implements basic CLI interface for the backup client
This PR ultimately adds in CLI capability for the guardian backup tool, allowing you to both pass in command line arguments into guardian-backup as well as allowing you to package the tool into various formats. Ideally I would have liked to also create a native image using graalvm but it turns out using graalvm with akka ecosystem doesn't appear to be that well support (mainly due to reflection reasons) but even basic things such as logback causes problems for the same reason so I will leave this for now.
The PR also adds standard basic configuration, i.e. a `logback.xml` so you can see basic logs as well as configuring akka to log through that logback.
A basic smoke style test has also been created where we pass cli command …
=> Implement CLI for backup

core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientInterfaceSpec.scala
This change implements actual JSON streaming for each individual element of the array rather than streaming it in all at once. 
Even though we are using akka-streams-json which is a streaming JSON parser, if you use it in its default configuration the streaming will just apply to the underlying `ByteString`. In order to get the behaviour we want where we stream each individual element in the JSON array rather than parsing it in all at once we need to use the `AsyncParser.UnwrapArray`.
This PR only updates the tests but since the actual restore will be using the same parsing mode we should make sure it works this way. As a bonus this should reduce some of the GC/memory pressure in the tests, since we are actually streaming the individual JSON elements as intended
=> Use JSON Array streaming in tests

build.sbt, cli-backup/src/test/scala/io/aiven/guardian/kafka/CliSpec.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/App.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/Entry.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/RestoreApp.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/S3App.scala, cli-restore/src/test/scala/io/aiven/guardian/kafka/CliSpec.scala, core-restore/src/main/scala/io/aiven/guardian/kafka/restore/RestoreClientInterface.scala, core-restore/src/test/scala/io/aiven/guardian/kafka/restore/MockedRestoreClientInterface.scala, restore-s3/src/main/scala/io/aiven/guardian/kafka/restore/s3/RestoreClient.scala, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientSpec.scala
This PR implements CLI for the restore portion of guardian.
The structure of the PR is pretty much the same as the earlier one that implemented CLI for backup (see https://github.com/aiven/guardian-for-apache-kafka/pull/83) with some additional notes/exceptions
* A
```scala
try backup.Main.main(args.toArray)
catch {
case _: Throwable =>
}
```
was added to the `CliSpec` tests for restore and the already existing backup. This is necessary because the `Main` part of 
`Restore` will throw an exception when initialized because not all of the data passed into main test actually exists (i.e. 
`backup-bucket` doesn't actually exist in S3). Note that the purpose of these tests is to see if the command line arguments are 
being correctly passed into the application's configuration, its **NOT** …
=> Implement CLI for restore

core-backup/src/main/scala/io/aiven/guardian/kafka/backup/KafkaClient.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientInterfaceSpec.scala, core/src/main/scala/io/aiven/guardian/kafka/codecs/Circe.scala, core/src/main/scala/io/aiven/guardian/kafka/models/ReducedConsumerRecord.scala, core/src/test/scala/io/aiven/guardian/kafka/Generators.scala
This PR adds `partition` field to `ReducedConsumerRecord`
When using Kafka transactional API to restore a backup we need the original partition and it will likely be required for a working implementation of https://github.com/aiven/guardian-for-apache-kafka/pull/96
=> Add partition to ReducedConsumerRecord

core-s3/src/test/scala/akka/stream/alpakka/s3/GeneratorsSpec.scala
The flaky tests were due to this fancepost error. I ran the tests on loop to make sure that it fixed the flakiness
Resolves: #114 
This just happened to be one character less than the legal amount for an s3 prefix.
=> Fix flaky test

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/BackupClientSpec.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala, core-s3/src/test/scala/akka/stream/alpakka/s3/GeneratorsSpec.scala, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala, core/src/test/scala/io/aiven/guardian/kafka/TestUtils.scala, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientSpec.scala
This PR skips tests from running if those tests rely on secrets for actual real services
Resolves: #118
The first part of the PR involves adding a ScalaTest tag that will ignore the test if a mandatory S3 secret is not resolvable (`ALPAKKA_S3_REGION_DEFAULT_REGION`). The tag's are nice abstraction since you can apply them optionally and easily to existing tests.
The second part of the PR needs some context explanation. The primary goal of this PR is solving #118 where S3 secrets are not resolved in CI tests by PR's that are created from forks. Annoyingly when secrets are not resolved this way, rather than unset'ting the environment variable you just get an empty environment variable and/or some of the env vars are missing since the others are statically defined (i.e. …
=> Skip integration tests from running if secrets not available

core/src/test/scala/io/aiven/guardian/kafka/TestUtils.scala
When checking for environment variables existing we also need to check that the environment variable doesn't evaluate to an empty string
The error that we are getting for forked PR's is so empty strings is what its actually being evaluated to.
```
[info] - backup method completes flow correctly for all valid Kafka events *** FAILED ***
[info]   NullPointerException was thrown during property evaluation.
[info]     Message: Access key ID cannot be blank.
```
=> Check if evaluated environment variable is empty string

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala
Increases the timeout for S3 related tests to 10 minutes
5 minutes can be too short, caused https://github.com/aiven/guardian-for-apache-kafka/runs/5383900785?check_suite_focus=true to fail
=> Increase timeout to 10 minutes

project/plugins.sbt
Updates to sbt-coveralls 1.3.2 as well as removing the old workaround
=> Update sbt-coveralls to 1.3.2

core-restore/src/main/scala/io/aiven/guardian/kafka/restore/RestoreClientInterface.scala
Methods that are meant to be private were not originally marked as private
=> Fix private methods in RestoreClientInterface

build.sbt
Makes sure that `core-cli` is available in the classpath when creating a package for the cli projects
`publishArtifact := false` which was defined in `cliSettings` was causing the sbt-native-package to completely skip the `*-core-cli.jar` in the classpath which caused the app to fail to run with
```
backup-0.1.0-SNAPSHOT ./bin/guardian-for-apache-kafka-cli-backup 
Exception in thread "main" java.lang.NoClassDefFoundError: io/aiven/guardian/cli/options/Options$
at io.aiven.guardian.kafka.backup.Entry.<init>(Main.scala:56)
at io.aiven.guardian.kafka.backup.Main$.<init>(Main.scala:104)
at io.aiven.guardian.kafka.backup.Main$.<clinit>(Main.scala:104)
at io.aiven.guardian.kafka.backup.Main.main(Main.scala)
Caused by: java.lang.ClassNotFoundException: io.aiven.guardian.cli.options.Options$
at …
```
=> Fix core-cli missing from classpath

README.md
This PR fixes the github-actions badge so that it refers to the `main` branch.
The previous version was checking that ALL github actions was passed/failed where as in reality we only want to check that the main branch is passing (otherwise someone can make a PR with a failing CI that will reflect in the badge).
=> Fix github-actions badge

.github/workflows/ci.yml, build.sbt
This PR fixes docs publishing for Guardian by using a SSH key that has permissions to push to a different github branch
See https://github.com/webfactory/ssh-agent#usage for implementation details.
=> Add ssh-key to publish docs

.github/workflows/ci.yml, build.sbt
Sets the git user and email for the github pages publish step.
Since there is no checkout for the publish step the git user/email is not being set, this change rectifies that problem.
=> Set git user and email

.jvmopts, project/plugins.sbt
Updates to latest parboiled  which fixes the issues of needing specific JVM parameters due to changes to JDK's `unsafe`
I just checked on my system whether the latest version works with JDK11/JDK17 and it works without needing the `.jvmpopts`
=> Update latest parboiled

.scala-steward.conf
This change configures scala-steward to always update the PR's it creates
Due to our configuration of our branch merging strategy, whenever the base branch is out of date scala-steward doesn't update the PR's (example is https://github.com/aiven/guardian-for-apache-kafka/pull/140). This PR fixes the issue.
=> Configure scala-steward to always update PR

build.sbt, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/Main.scala, core-backup/src/main/resources/reference.conf, core-restore/src/main/resources/reference.conf, core/src/main/resources/reference.conf, docs/src/main/paradox/backup/configuration.md, docs/src/main/paradox/restore/configuration.md
This PR fixes up how the kafka-clients (i.e. configuration specifically for the underlying official Java Kafka Client) configuration is applied.
In summary this PR fixes the issue of passing in configuration via either environment variables or java system properties into the underlying official Kafka client. This is necessary for settings such as ssl/tls, username, password etc etc. This is especially important given that as of now, the cli tool doesn't let you set these settings via command line arguments (its an open point about which command line arguments the cli tool/s should provide)
Notes:
* A lot of settings from the main `core` `reference.conf` was moved to the respective modules so that the documentation could correctly display which `reference.conf` settings are relevant for …
=> Fix kafka-clients configs

docs/src/main/paradox/backup/design.md, docs/src/main/paradox/backup/index.md, docs/src/main/paradox/persistence/s3/index.md, docs/src/main/paradox/restore/index.md, project/plugins.sbt, project/project-info.conf
This PR enables sbt-paradox-project-info by using the latest release
In the previous release of sbt-paradox-project-info the `levels` field was mandatory and hence it couldn't be omitted. I resolved this in the latest release which means we can now enable sbt-paradox-project-info.
The PR also moves info about `backup` from `index.md` to `design.md` since it make more sense there.
=> Enable sbt-paradox-project-info

cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/App.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/S3App.scala, core-restore/src/main/scala/io/aiven/guardian/kafka/restore/RestoreClientInterface.scala
Logs errors if an uncaught exception is thrown in one of the streams
The solution for the `cli-restore` is not that typical but that is due to https://github.com/typelevel/jawn/pull/438  and https://discuss.lightbend.com/t/working-with-eof-for-a-source-flow/9481
=> Log errors if a stream terminates unexpectedly

cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/App.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/Main.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/Main.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/S3App.scala, core-restore/src/main/resources/reference.conf
Fixes the problem where cli-backup was immediately terminated. Also added a log message when a shutdown is detected
=> Prevent cli-backup from immediately terminating

cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/Main.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/KafkaClient.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientInterfaceSpec.scala, core-restore/src/main/scala/io/aiven/guardian/kafka/restore/KafkaProducer.scala, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala, core/src/main/scala/io/aiven/guardian/kafka/models/ReducedConsumerRecord.scala, core/src/test/scala/io/aiven/guardian/kafka/Generators.scala
Add functionality to handle the case where the kafka `ProducerRecord` key happens to be null
Self explanatory, forgot to handle this case. Note that at some point in future we should add tests to handle the case where the `key` is null.
=> Handle null keys

build.sbt, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/App.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/Main.scala, cli-backup/src/test/scala/io/aiven/guardian/kafka/CliSpec.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/Main.scala, core-cli/src/main/scala/io/aiven/guardian/cli/MainUtils.scala
The https://github.com/aiven/guardian-for-apache-kafka/pull/165 PR didn't completely correctly implement the logic where the CLI backup never terminates.
=> Update never terminate logic

core-cli/src/main/resources/logback.xml
Current CLI logging doesn't have a timestamp, this PR adds it.
=> Add timestamp to cli logging

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/MockedS3BackupClientInterface.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/Main.scala, cli-backup/src/test/scala/io/aiven/guardian/kafka/CliSpec.scala, core-backup/src/main/resources/reference.conf, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/KafkaClient.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/configs/Backup.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedBackupClientInterface.scala, docs/src/main/paradox/backup/configuration.md, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientSpec.scala
This PR sets the `commit-timeout` configuration for the Alpakka Kafka consumer to be based on the configured `time-configuration` plus an extra configurable `commit-timeout-buffer`
Since Guardian has manual control over committing cursors from read topics which it overrides it makes sense for Guardian to also set the `commit-timeout` option due to the fact that the user has no control over commit strategies. In other words, if you set a `time-configuration` of `1 minute` then the `commit-timeout` should be larger than that because Guardian will commit the cursor around every minute.
The `commit-timeout-buffer` is there to give us some headroom (delays in commits, latency between kafka cluster and the client since timestamp is based off Kafka's cluster timestamp etc etc). I set the buffer …
=> Set commit-timeout based on timeConfiguration

backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/BackupClientSpec.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/App.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/Main.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/Main.scala, cli-restore/src/main/scala/io/aiven/guardian/kafka/restore/S3App.scala, compaction-gcs/src/main/scala/io/aiven/guardian/kafka/compaction/gcs/StorageClient.scala, compaction-s3/src/main/scala/io/aiven/guardian/kafka/compaction/s3/StorageClient.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/KafkaClient.scala, core-cli/src/main/scala/io/aiven/guardian/cli/MainUtils.scala, core-cli/src/main/scala/io/aiven/guardian/cli/options/Options.scala, core-restore/src/main/scala/io/aiven/guardian/kafka/restore/RestoreClientInterface.scala, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala
Improves logging by adding some DEBUG statements but mainly allowing the `cli` tool to specify an alternative `logback.xml` (so you can turn on `DEBUG` level logging for example)
Changes are self explanatory but here are some notes
* `StrictLogging` was changed to `LazyLogging` to ensure that the `logger` class gets initialized after configuring the `logback` file (`LazyLogging` just assigns the `logger` to a `lazy val` so it only initializes the first time `logger` is referenced). I am not sure this is strictly necessary but its best to be safe
* Unfortunately due to the design of logback, testing that the configuration has changed successfully is not trivial. I tried this out locally and can confirm it works but we would have to use some other logging library to properly test for these …
=> Improve logging for CLI

cli-backup/src/test/scala/io/aiven/guardian/kafka/backup/CliSpec.scala, cli-restore/src/test/scala/io/aiven/guardian/kafka/restore/CliSpec.scala, core/src/test/resources/logback.xml
Moves the `CliSpec` to their respective packages
Due to currently both tests being in the same `io.aiven.guardian.kafka` but in different package's, if one of the tests fail then you don't know which one does.
=> Move CliSpec's to to their respective package

cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/Main.scala, cli-backup/src/test/scala/io/aiven/guardian/kafka/backup/CliSpec.scala, core/src/test/scala/io/aiven/guardian/kafka/Cancellable.scala
Solves the issue where `CliSpec` does not terminate if you don't provide the correct S3 credentials
Resolves: https://github.com/aiven/guardian-for-apache-kafka/issues/173
The main issue was resolved in the `Reorder when initializedApp is set so CliSpec terminates` commit, basically `initializedApp.set(Some((app, p)))` happens earlier which is what `CliSpec` polls on for the test.
`Make CliSpec computation cancellable` is a bonus which makes the `CliSpec` cancelled (normally `Future`'s cannot be cancelled).
=> Fix termination issue clispec

core-cli/src/main/scala/io/aiven/guardian/cli/options/Options.scala
Since `kafka-topics` is shared both by restore and backup the help parameter should be general and not mention backup 
Self explanatory
=> Generalize kafka-topics cli help

build.sbt, project/project-info.conf
Fixes incorrect documentation links.
Self evident
=> Fix incorrect documentation links

docs/src/main/paradox/application/design.md, docs/src/main/paradox/application/index.md, docs/src/main/paradox/application/logging.md, docs/src/main/paradox/application/packaging.md, docs/src/main/paradox/general-architecture/index.md, docs/src/main/paradox/general-architecture/logging.md, docs/src/main/paradox/index.md
This PR adds information about logging in Guardian. It also separates out the `application` documentation into different sections. 
Self explanatory
=> Add logging/logback documentation

.github/workflows/format.yml
This patch improves security around GitHub Workflows:
For the `format.yml` workflow:
* Set the default workflow permissions to `read` - because this workflow does not need to modify anything in the project.
* Do not let `actions/checkout` persist (write to disk) the GitHub token - because this workflow does not need to modify anything in the project. And prevents other actions to look at the token.
* Remove the `env:  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}` section - this shares the token with every step. It is better to only do this on a per-step basis.
I am trying to understand the other two workflows. Both of those have the GITHUB_TOKEN and S3 tokens shared globally with all jobs, which doesn't feel right. This is simple to fix but I see a note on top of both `ci.yml` and …
=> Harden the GitHub Workflows

.github/workflows/ci.yml, build.sbt
Only expose S3 secrets when we run tests rather than the entire pipeline
Implements the solution suggested at https://github.com/aiven/guardian-for-apache-kafka/pull/186#issuecomment-1089450741.
=> Only expose S3 secrets in sbt test

build.sbt
simplifies generated RPM executable name to `guardian-(backup|restore)` instead of `guardian-for-apache-kafka-cli-*`
`guardian-for-apache-kafka-cli-*` is a bit of a tongue twister
=> update generated bin files names

core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala
Due to an existing limitation with `SubFlow` (details in comments in PR), any exceptions that get thrown in the `SubFlow` are suppressed and cause the stream to retry and hence loop indefinitely.
References: https://github.com/aiven/guardian-for-apache-kafka/issues/221
The core problem is not solvable right now (at least without upstream changes) however we can at least log the exception so users know whats going on. This is particularly problematic for silly mistakes such as getting S3 credentials wrong as currently there is no feedback at all.
=> Log exceptions thrown inside SubFlow

cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/App.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/KafkaClient.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/KafkaClientInterface.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedKafkaClientInterface.scala
This PR does 2 changes, each change being represented by its own commit. The first change makes sure that the SubFlow's don't occur concurrently and due to this change we can also solve the issue of not having a proper drain control (see https://doc.akka.io/docs/alpakka-kafka/current/consumer.html) with these changes being done in the second commit.
References: #178 
Resolves: #80 
So it turns out that as documented in https://doc.akka.io/docs/akka/current/stream/stream-substream.html#splitwhen-and-splitafter its possible to have multiple sub flow's occurring at the same time. Initially I thought this would be a non issue since the kafka records we get are ordered  over time with a timestamp so it wasn't possible to parallelize anyways however it turns out if you are getting a lot of …
=> Disable concurrent executions and enable draining control

backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala
This PR fixes the memory leak that was discovered in https://github.com/aiven/guardian-for-apache-kafka/pull/232
Turns out there is an already existing function in S3 Alpakka's client called `S3.getObjectMetadata` which is also meant to be used for checking for the existence of an obejct.
=> Fix stream leak by using appropriate function

backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala
Explicitly use `ExecutionContext.parasitic` when doing non-block `.map` operations on a `Future`.
Non blocking CPU operations done inside of a `.map` on a `Future` should explicitly use `ExecutionContext.parasitic` as to not overload the default `ExecutionContext` (which is typically a `ForkJoinPool` or some variant).
Note that `ExecutionContext.parasitic` executes the task immediately on the current thread so its designed to be used for "cheap" operations (such as boxing data structures or using constructors).
=> Use ExecutionContext.parasitic on non-blocking map operations

backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala
Ever since the last change to use explicit `ExecutionContext.parasitic`, the `(implicit executionContext: ExecutionContext)` is no longer neccessary.
=> Remove redundant implicit ExecutionContext

build.sbt, docs/src/main/paradox/application/logging.md, docs/src/main/paradox/ci.md, docs/src/main/paradox/doc-generation.md, docs/src/main/paradox/general-architecture/logging.md, docs/src/main/paradox/security.md, docs/src/main/paradox/testing/s3.md, project/plugins.sbt
Updates paradox dependency while also implementing the `@github` [directive](https://developer.lightbend.com/docs/paradox/current/directives/linking.html#github-directive) for github references. 
Resolves: #187 
Read the referenced issue to get more details about why its done this way. The new version of paradox fixes the bug referenced in the issue so we are now able to use the github directive. Actual markdown changes are quite self explanatory.
=> Update paradox and use github directive

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala, core/src/test/scala/io/aiven/guardian/kafka/Generators.scala, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientSpec.scala
Rather than using a constant Kafka consumer group, randomly generate them using scalacheck
This PR is a theoretical attempt to both help solve flaky tests as well as improve the performance of tests (I have a suspicion that reusing the same constant consumer group amongst a lot of tests against a real kafka cluster is causing the tests to runs slower). Finally this will be useful in the future when parallelising tests.
Note that the large diff is due to scalafmt, you can hide whitespace in the github diff viewer if you want to view the diff more easily.
=> Randomly generate Kafka Consumer Group's in tests

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala
In the previous PR at https://github.com/aiven/guardian-for-apache-kafka/pull/258 I forgot to filter out generated kafka consumer groups if they happen to be exactly the same.
The PR also adds logging statements for buckets (some tests was missing this).
=> Make sure kafkaConsumerGroupGen doesn't generate duplicates

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientSpec.scala
Move the cleanupTopics into an `onComplete` method on the `Future` so it always occurs even if there is an exception in the test
In the previous PR at https://github.com/aiven/guardian-for-apache-kafka/pull/276 topicCleanup was added however since it was a normal statement in the `for` comprehension on a `Future` it wouldn't trigger if the test would throw an exception for some reason. This change fixes that (`onComplete` will trigger regardless if the `Future` completes successfully or not).
=> Make cleanTopics also trigger if exception occurs

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala, cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/App.scala, cli-backup/src/test/resources/logback.xml, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientControlWrapper.scala, core/src/test/resources/application.conf, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientSpec.scala
Adds a mechanism to shut down the backup clients after each individual test is run
Due to the tests not being cleaned up properly a lot of output was being logged about clients not being able to connect anymore since the test was already finished. Another commit has also been added to remove the akka dead letter logging, i.e.
```
[INFO] [akkaDeadLetter][09/02/2022 20:10:30.238] [MinioS3BackupClientSpec-akka.actor.default-dispatcher-21] [akka://MinioS3BackupClientSpec/system/IO-TCP/selectors/$a/23] Message [akka.actor.ReceiveTimeout$] to Actor[akka://MinioS3BackupClientSpec/system/IO-TCP/selectors/$a/23#-1892879735] was not delivered. [4] dead letters encountered. If this is not an expected behavior then Actor[akka://MinioS3BackupClientSpec/system/IO-TCP/selectors/$a/23#-1892879735] may …
```
=> Properly cleanup BackupClient after test finishes

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/MockedKafkaClientBackupClientSpec.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala
Moves the `Creating many objects in a small period of time works despite S3's in progress multipart upload eventual consistency issues` into a new `MockedKafkaClientBackupClientSpec` class.
Having the `Creating many objects in a small period of time works despite S3's in progress multipart upload eventual consistency issues` test inside of `RealS3BackupClientSpec` doesn't make sense since its using a mocked Kafka interface. Furthermore with the https://github.com/aiven/guardian-for-apache-kafka/pull/196 PR, having this test inside of `RealS3BackupClientSpec` causes it be redundantly run multiple times and also unnecessarily start Kafka cluster.
=> Move mock tests into MockedKafkaClientBackupClientSpec

.scala-steward.conf
Due to akka changing their license an incompatible BSL in v 2.7.x, this PR limits scala steward so that it will never create a PR for an akka version that is not license compatible.
See https://github.com/akka/akka/pull/31561, https://www.lightbend.com/blog/why-we-are-changing-the-license-for-akka and https://www.lightbend.com/akka/license-faq
=> Pin akka to version 2.6 due to license change

build.sbt, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/Main.scala, docs/src/main/paradox/testing/s3.md
Adds a CLI utility for cleaning up buckets that have been left over in S3 tests
This functionality is added as a standard `Main` class however due to the ability CLI tool to do damage to an S3 account its placed in the `test` scope, it's not packaged and it has to be executed manually via sbt. To further improve the safety of the tool, you must provide a mandatory `prefix` parameter when running it.
Documentation has also been added on how to use the tool.
=> Add CLI bucket cleanup utility

docs/src/main/paradox/testing/index.md
This PR adds documentation on how to deal with property/flaky tests for Guardian.
=> Add documentation for property/flaky tests

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala
Makes sure that the argument to throttle is always at least 1
The argument to throttle must always be greater than 0
```
[info] - Round-trip with backup and restore *** FAILED ***
[info]   IllegalArgumentException was thrown during property evaluation.
[info]     Message: requirement failed: cost must be > 0
[info]     Occurred when passed generated values (
```
With the division the result could end up being truncated to 0 so this PR makes sure it is always at least 1.
=> Specify max to throttle argument

project/plugins.sbt
This PR updates scoverage.
Ever since https://github.com/aiven/guardian-for-apache-kafka/pull/261 was merged scoverage wasn't working, this PR fixes that. See https://github.com/scoverage/sbt-coveralls/issues/199 and https://github.com/scoverage/scalac-scoverage-plugin/pull/497 for the reason why scoverage broke in the update
=> Fix scoverage

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/Main.scala, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3TestUtils.scala
Creates a `S3TestUtils.cleanAndDeleteBucket` method.
There was a lot of duplication in test code when it came to cleaning buckets, this was all refactored into a single `S3TestUtils.cleanAndDeleteBucket` method.
=> Refactor cleaning up S3 buckets into its own method

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/MockedKafkaClientBackupClientSpec.scala, core-restore/src/test/scala/io/aiven/guardian/kafka/restore/RestoreClientInterfaceSpec.scala, core/src/test/scala/io/aiven/guardian/kafka/Generators.scala
Modifies the `padTimestampsMillis` so that it accepts the Scala `Range` type rather than Int and modifies the `MockedKafkaClientBackupClientSpec` so that it uses `Range.inclusive(1000, 1000)` for `padTimestampsMillis` which removes the randomness from the test. `tailingSentinelValue` has also been renamed to `trailingSentinelValue`.
Resolves: #290
Due to the computation of `kafkaDataWithTimePeriodsGen(100, 100, 1000, tailingSentinelValue = true)` generating random values along with a `PeriodFromFirst` configuration of `1 second` created situations where the `MockedKafkaClientBackupClientSpec` can randomly fail due to not creating a processing boundary for calculating the time slice and hence some data being missed in the final match.
To fix this `padTimestampsMillis` has been changed to a …
=> Use Range for padTimestampsMillis to fix test flakiness

core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientInterfaceSpec.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedBackupClientInterface.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedKafkaClientInterface.scala, core/src/test/scala/io/aiven/guardian/kafka/Generators.scala
Adjusts various mocks so that they are able to handle the suspend/resume case in Guardian. Also adds a test which makes sure the mocks work.
The context of this PR is for the gzip compression PR at https://github.com/aiven/guardian-for-apache-kafka/pull/196. In that gzip compression PR I want to add a test which makes sure that restarting the tool between changing the gzip configuration works (i.e. first start guardian with gzip compression on, shut down guardian, then turn on Guardian again with gzip compression off). While its possible to test this using a real Kafka/S3, its excessive since I only want to test that the compression changes apply.
The basis of the PR is to add data structures (`backedUpData`/`commitStorage`) that is shared between `mockOne`/`mockTwo` in order to share the …
=> Adjust Mocks to handle kafka commits

cli-backup/src/test/scala/io/aiven/guardian/kafka/backup/CliSpec.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientInterfaceSpec.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/MockedBackupClientInterface.scala, core-restore/src/test/scala/io/aiven/guardian/kafka/restore/RestoreClientInterfaceSpec.scala
This PR contains some minor fixes, i.e.
* In the previous PR at https://github.com/aiven/guardian-for-apache-kafka/pull/302 some parameter names
* There is an issue whereby slf4j complains that logs were made during initialisation of logging, adding in `StrictLogging` into the traits forces the initialisation to happen instantly.
=> Minor fixes

build.sbt
Updates scalafmt to the latest 1.16.0 release
Just a standard version bump
=> Update to scalacheck 1.16.0

.github/workflows/dependency-graph.yml
Submits a dependency graph to Github so it can report on security issues
See https://github.com/scalacenter/sbt-dependency-submission
=> Submit dependency graph to Github dependency submission API

build.sbt
Removes Scala 2.12 support from Guardian.
When Lightbend did the last release of the Alpakka modules before BSL license change they forgot to make a release for Scala 2.12 which is causing problems with the github dependency uploader (see https://github.com/aiven/guardian-for-apache-kafka/actions/runs/3232747596/jobs/5295086621).
Scala 2.12 can be re-introduced when Pekko comes along
=> Remove Scala 2.12 support

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala
Timeouts are being caused with Guardian in actively running tests
This should at least prevent the tests from timing out.
=> Increase timeout due to tests failing

.github/workflows/ci.yml, build.sbt, project/plugins.sbt
Updates Scala version.
Note that `Build and Test (ubuntu-latest, 2.13.8, temurin@11)` CI check won't run because its not triggered (due to change of Scala version). One this PR is merged the github status checks need to be updated.
=> Update Scala to 2.13.10

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala
Adds a `ShowConfig` to reduce output of identical elements of collections in a diff
When one of the test fails specifically due to structures not being matched correctly, currently it will also output all of the identical elements in the diff. Due to the size of the data structures we are dealing with (i.e. many mags) this output tends to be massive.
Using this `ShowConfig` significantly reduces the output, see https://diffx-scala.readthedocs.io/en/latest/usage/output.html?highlight=ShowConfig#skipping-identical for more info.
=> Add a diffx ShowConfig to reduce test failure output

.github/workflows/format.yml
Updates scalafmt native to the latest version as well as only applying scalafmt to change files.
Version updates is self explanatory. The `--mode diff-ref=origin/main` argument means that scalafmt will only format files that have changed from origin main (aka git ratcheting), improving the speed of scalafmt. Note that the `--list` needs to be provided since we are overriding the `arguments` (i.e. if you don't supply `arguments` then it defaults to `--list`)
=> Improve github scalafmt-native-action

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/BackupClientChunkState.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientTest.scala, core/src/test/scala/io/aiven/guardian/kafka/TestUtils.scala, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientTest.scala
Resolves a problem related to flaky tests as well as improvements to when tests fail
The main cause of the recent flaky tests is that S3 is not deterministic in the result ordering when we get bucket result contents, this was causing problems in tests that was specifically needing two keys, i.e. `getKeysFromTwoDownloads` (this is resolved in the `Sort the keys before returning them in getKeysFromTwoDownloads` commit). The other commits should be self explanatory.
=> Fix flaky tests

core-backup/src/test/scala/io/aiven/guardian/kafka/backup/CompressionSpec.scala
Sometimes the gzip compression spec fails because of a timeout. This seems to happen when the data generated from scalacheck happens to have really bad entropy which causes the test to timeout.
=> Override PatienceConfig for gzip compression test

core-backup/src/test/scala/io/aiven/guardian/kafka/backup/CompressionSpec.scala
Uses `AkkaStreamInitializationConstant` instead of an overridden `PatienceConfig` to account for a test taking a long time. Also as a bonus extending `AkkaStreamTestKit` means that that `ActorSystem` is properly shut down after test completes.
The reason provided in the previous solution to the problem at https://github.com/aiven/guardian-for-apache-kafka/pull/352 was likely a red herring. The issue is much more likely to be that when akka-streams is used for the first time have an initialisation delay and we forget to account for it with `AkkaStreamInitializationConstant`.
=> Use explicit timeout rather than overriding PatienceConfig

build.sbt
Updates the scalatest scalacheck version. Also refactors the artifact into a variable `scalaTestScalaCheckArtifact` due to the fact that the artifact also happens to have a version (this is quite unique to scalatest).
The larger diff is due to scalafmt, make sure to set diff to hide whitespace.
=> Update scalatest scalacheck artifact

core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientControlWrapper.scala
Only do a `shutdown` if a control is defined
Solves the problem with the following stack trace
```
Error:  [01/12/2023 15:49:19.612] [RealS3BackupClientSpec-akka.actor.default-dispatcher-7] [akka.dispatch.Dispatcher] null
java.lang.NullPointerException
at io.aiven.guardian.kafka.backup.BackupClientControlWrapper.shutdown(BackupClientControlWrapper.scala:22)
at io.aiven.guardian.kafka.backup.s3.RealS3BackupClientTest.$anonfun$$init$$38(RealS3BackupClientTest.scala:251)
at io.aiven.guardian.kafka.TestUtils$ScalaFutureExtensionMethods.$anonfun$onCompleteLogError$1(TestUtils.scala:44)
at io.aiven.guardian.kafka.TestUtils$ScalaFutureExtensionMethods.$anonfun$onCompleteLogError$1$adapted(TestUtils.scala:39)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
at …
```
=> Only shutdown if control is defined

build.sbt, core/src/test/scala/io/aiven/guardian/kafka/Generators.scala
Replaces fork of scalacheck with official upstream one and as a result implements `listOfFillCond` natively.
Initially a fork of scalacheck was made in order to implement the ability to create a continuously growing generator. The fork was done because at the time I thought it was not possible to implement this without modifying the core of scalacheck. It turns out that I was incorrect in this, scalacheck has a `Gen.infiniteLazyList` which can be used to implement this functionality (see https://github.com/typelevel/scalacheck/pull/849#issuecomment-1264599632)
=> Remove scalacheck fork by implementing buildableOfCollCond

build.sbt
Currently the `scalaTestScalaCheckArtifact` is manually hardcoded as `scalacheck-1-17` however the `1-17` actually corresponds to the epic/major part of `scalaCheckVersion` (i.e. `1.17` from `1.17.0`).
This PR makes it so that we calculate the `1-17` part from `scalaCheckVersion`
The PR adds a function called `scalaTestPlusScalaCheckVersion` which derives the version from `scalaCheckVersion` and uses that for `scalaTestScalaCheckArtifact`.
=> Calculate org.scalatestplus scalatest artifact from scalacheck version

build.sbt, docs/src/main/paradox/index.md, project/LicenseReport.scala, project/plugins.sbt
Integrates [sbt-license-report](https://github.com/sbt/sbt-license-report) into paradox which provides an transitive scan of all dependencies licenses directly into guardian documentation.
The approach used here is similar to what was done in Pekko https://github.com/apache/incubator-pekko/pull/319. The only major difference is that I opted to remove `Column.OriginatingArtifactName` from the columns because it caused the generated report to have way too much noise. `Column.OriginatingArtifactName` means that the report displays which dependencies are coming from which artifacts but since Guardian is meant to be used as an application its not that relevant (also as you can see from the generated report all of our dependencies are Apache/MIT/GPL etc etc so its not like there are some …
=> Integrate sbt-license-report

project/plugins.sbt
Current sbt build is broken with latest sbt-site updated.
sbt-site split out its paradox support into a separate plugin, see https://www.scala-sbt.org/sbt-site//migration-guide.html#migrating-from-version-1-4-x-to-1-5-x
=> Change sbt-site to sbt-site-paradox

.scala-steward.conf
Pekko currently doesn't have a release and due to this we are using snapshots.
Due to the usage of snapshots and the fact that they update nightly, its best to pin pekko snapshot updates
=> Pin Pekko snapshot dependencies for now

.github/workflows/ci.yml, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/BackupClientSpec.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/MockedKafkaClientBackupConsumerSpec.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientTest.scala, build.sbt, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala, core/src/test/scala/io/aiven/guardian/kafka/TestUtils.scala, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientTest.scala
Uses AWS OIDC provider for credentials rather than raw key/secret
Using github's secrets has the issue where if someone creates a pull request that it outside of the Aiven org (which ultimately means creating a fork) then github-actions will not expose the secrets for security reasons.
The proper way to solve this problem is to use the OIDC provider https://github.com/aws-actions/configure-aws-credentials which afaik creates the same key/secret in environment variables however those specific key/secret that is generated is temporary so even if a bad actor gets access to them they would have already been expired.
With the latest version of sbt-github-actions merged (see https://github.com/aiven/guardian-for-apache-kafka/pull/410) its now possible to do this.
=> Use S3 OIDC credentials provider

.github/workflows/ci.yml, build.sbt
Increases role timeout to 4 hours
This is what the AWS OIDC is configured for
=> Increase AWS role timeout to 4 hours

.github/workflows/scala-steward.yml
Run Scala Steward as a GitHub Action to allow better compatibility with other actions in this repository.
Some GitHub Actions fail when invoked due to a Pull Request from a fork. This means all external Scala Steward submitted PRs have failing CI runs and we don't know if a dependency update will cause issues. Using a GitHub App combined with the GitHub Action in the repository gets around this and CI should be able to run correctly.
=> github: add scala steward action

README.md
Fixed a broken link from README to reference documentation following repo move. 
Using the correct link instead of the broken one seemed like the right way to go :)
=> Fixed link to reference docs

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/BackupClientSpec.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/MockedKafkaClientBackupConsumerSpec.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientTest.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/BackupClientInterfaceTest.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/CompressionSpec.scala, core-backup/src/test/scala/io/aiven/guardian/kafka/backup/ConfigurationChangeRestartSpec.scala, core-restore/src/test/scala/io/aiven/guardian/kafka/restore/RestoreClientInterfaceTest.scala, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala, core/src/test/scala/io/aiven/guardian/pekko/AnyPropTestKit.scala, core/src/test/scala/io/aiven/guardian/pekko/PekkoStreamTestKit.scala, restore-s3/src/test/scala/io/aiven/guardian/kafka/restore/s3/RealS3RestoreClientTest.scala
The PR adds in the test name when doing `logger.info`
The are 2 primary changes that allow for us to automatically add the test name to logging
* Configure the code so that we use a TestFixture. You can see https://stackoverflow.com/a/14836709/1519631 but a Fixture is ScalaTest terminology for passing in context via a parameter into an anonymous function (in ScalaTest your tests are written as anonymous functions). In this case use `TestData` (which contains data about the test being run) for our test fixture
* ScalaLogging's [LoggingTakingImplicit](https://github.com/lightbend-labs/scala-logging#using-scala-logging) which allows you to create a logger that takes in this `TestData`. Since its an implicit its verified at compile time, but this is what allows us to do `logger.info` which …
=> Automatically include test name when logging

.github/workflows/dependency-graph.yml
Add write permission to github job
Default github permissions have changed so this needs to be explicit, otherwise you get this issue https://github.com/Aiven-Open/guardian-for-apache-kafka/actions/runs/6016582389/job/16320935902
=> Fix permissions for dependency graph submission

.scala-steward.conf, build.sbt
Updates to Pekko full releases
Resolves: #xxxxx
All of the relevant Pekko modules have their full releases. Also no longer need the Apache Maven Snapshots repo
=> Update Pekko to full releases

.github/workflows/dependency-graph.yml, .github/workflows/format.yml
Updates github checkout actions to latest version
Self explanatory, note that the other github actions are generated by sbt-github-actions so there is a separate PR for this (see https://github.com/Aiven-Open/guardian-for-apache-kafka/pull/485)
=> Update github checkout actions to 4

build.sbt, core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala
Updates to latest snapshot of Pekko which fixes currently existing issues with `splitAfter`/`SubstreamCancelStrategy`.
Since https://github.com/apache/incubator-pekko/pull/252 was merged and released as a snapshot, this PR applies the changes necessary as documented in the [migration steps](https://pekko.apache.org/docs/pekko/snapshot/project/migration-guide-1.0.x-1.1.x.html#source-splitwhen-flow-splitwhen-source-splitafter-flow-splitafter-behavioural-change).
In summary, the relevant behavioural changes is that rather than `splitAfter` using a `SubstreamCancelStrategy` it instead resuses the already existing [`SupervisionDecider`](https://github.com/Aiven-Open/guardian-for-apache-kafka/blob/db4f3feae5948248a218179e830bb71ad20f23ba/cli-backup/src/main/scala/io/aiven/guardian/kafka/backup/A …
=> Remove deprecated splitAfter functionality

.github/workflows/format.yml
Updates the scalafmt github action to version 3
The notable change in this updated version is that it no longer needs a hardcoded version, instead it can read the version from https://github.com/Aiven-Open/guardian-for-apache-kafka/blob/f294e464e9c4adc0bbf8bbe416414af4700312d8/.scalafmt.conf#L1 which means that scala-steward can now make proper scalafmt update PR's
=> Update scalafmt native github action

.github/workflows/scala-steward.yml
This change allows a manual trigger of Scala Steward instead of having to wait for the cron job
=> Add workflow dispatch
