README.md
=> Update README with trademark disclaimer

core-backup/src/main/scala/io/aiven/guardian/kafka/backup/BackupClientInterface.scala
This PR replaces `ByteStringElement` with `FlowWithContext`/`SourceWithContext` that has the `ByteString` as the main data and a `Start`/`Tail` that represents the context.
Currently Guardian uses `ByteStringElement` when constructing the final stream before it gets sent to the `Sink`s for persisting in storage. Akka-Stream already provides an abstraction called `SourceWithContext`/`FlowWithContext` that handles the exact same problem, see https://doc.akka.io/docs/akka/current/stream/stream-context.html.
This PR is also a reaction to and hence a precursor for adding gzip compression to Guardian. In conjunction with https://github.com/akka/akka/pull/31123 (if it gets merged or otherwise we will just make our own conversion methods) it becomes very easy to add g-zip compression since you …
=> Replace ByteStringElement with SourceWithContext/FlowWithContext

.github/workflows/format.yml, .scalafmt.conf, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/PureConfigS3HeadersSpec.scala, core/src/test/scala/io/aiven/guardian/kafka/Generators.scala
This PR updates to latest version of scalafmt as well as applying any changes
N/A
=> Update and apply scalafmt

SECURITY.md
Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>
Fixing typo in security document.
=> Fix typo in SECURITY.md document

.github/workflows/ci.yml, build.sbt
Updates the Scala version.
Not done by Scala steward because it doesn't regenerate sbt-github-actions
=> Update Scala versions

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/MinioContainer.scala, core-s3/src/test/scala/io/aiven/guardian/kafka/s3/MinioS3Test.scala
Some very minor improvements to code.
=> Minor improvements to Minio/testcontainers

CONTRIBUTING.md, build.sbt, docs/src/main/paradox/index.md, docs/src/main/paradox/testing/index.md, docs/src/main/paradox/testing/s3.md
This PR improves documentation and gotcha's for testing
N/A
=> Improve documentation for testing

docs/src/main/paradox/persistence/s3/index.md, project/project-info.conf
This PR adds scaladoc references to the documentation
Self explanatory
=> Add scaladoc links to modules in documentation

docs/src/main/paradox/general-architecture/logging.md
Just fixes some incorrect grammer.
=> Fix incorrect grammer

build.sbt
=> Add Ryan to developer list

build.sbt
=> Add start year

backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala
=> Clarify code reference comment

backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala
There seems to be an eventual consistency issue whereby the deleting of a currently in progress upload doesn't transactionally complete the deletion of the in progress upload when the upload completes, in other words as server side entities its possible to have both an in progress upload along with the associated completed S3 object at the same time.
This PR filters any multipart upload listings that happen to already exist as S3 objects
References: #178 
Nothing special about the PR, only concern might be that the `logger.warn` statement can in reality spam the logs because it appears that if you happen to be running on a data set that creates lots of small keys very quickly (as is the case with the referenced issue). If this is the case I will make a future PR to reduce the log level …
=> Filter out in progress uploads that already exist as S3 objects

backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala
The log statement was printing current and previous the wrong way around.
=> Fix incorrect log statement

backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala
=> Remove dead code

backup-s3/src/main/scala/io/aiven/guardian/kafka/backup/s3/BackupClient.scala, backup-s3/src/test/scala/io/aiven/guardian/kafka/backup/s3/RealS3BackupClientSpec.scala
This PR fixes another bug when it comes to eventual consistency for S3 while also adding tests for multiple keys which covers the scenario where the bug occurred
When retrieving the initial state of currently in progress uploads from S3 we use the `S3.listMultipartUpload` however its possible to have a multipart upload entity with no parts. In the case of having a multipart upload with no parts it would trigger the `backupToStorageTerminateSink` branch which created empty `.json` files that have `null]` (those files are empty because the upload had no parts, the `null]` are meant to be appended to existing incomplete uploads that already have some data i.e. they have 1 or more parts).
This PR filters out all incomplete multipart uploads that have no parts in the `getCurrentUploadState` …
=> Filter out incomplete uploads that have no parts

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala
When making an S3 bucket in tests, check if it already exists and if it does so delete it (so the state is cleanup up) and then recreate it. Current behaviour is an error is thrown.
If a test fails with Scala's property check, scalatest will rerun the tests with the exact same generated data which means it will try and recreate a bucket which already exists on the previous test run. This PR makes it so that if a bucket already happens to exist and it has the correct permissions then we delete bucket contents, delete the bucket and recreate it.
Although its technically possible to just clean the bucket contents doing so is quite difficult because of the multipart upload state so its just easier to delete the bucket entirely.
=> Delete and recreate an S3 bucket in tests if it already exists

build.sbt
=> Update akka versions

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala
Retry with exponential backoff when cleaning up a bucket after a test
Due to eventual consistency in S3 you can get the following error in tests when trying to delete a bucket
```
22:17:17.607 [MockedKafkaClientBackupClientSpec-akka.actor.default-dispatcher-8] ERROR io.aiven.guardian.kafka.backup.s3.MockedKafkaClientBackupClientSpec - Error deleting bucket: guardian-7-pp2nufkryaezjmzi58
akka.stream.alpakka.s3.S3Exception: The bucket you tried to delete is not empty
at akka.stream.alpakka.s3.S3Exception$.apply(S3Exception.scala:37)
at akka.stream.alpakka.s3.impl.S3Stream$.$anonfun$unmarshalError$1(S3Stream.scala:607)
```
Using exponential backoff with a condition for this specific error solves the problem
=> Retry with backoff on deleting bucket in tests

build.sbt
=> Add Ahmed Sobeh as developer

core-s3/src/test/scala/io/aiven/guardian/kafka/s3/S3Spec.scala
Adds actor shutdown cleanup to S3Spec
The `super.afterAll()` points to https://github.com/aiven/guardian-for-apache-kafka/blob/cb5ebe4d131a7e0bb37701971ca7ae40f9438188/core/src/test/scala/io/aiven/guardian/akka/AkkaHttpTestKit.scala#L10-L15. The `super.afterAll()` cleanup is done within a `finally` block because its possible for the bucket cleanup to fail.
=> Add actor cleanup to S3Spec

.github/workflows/ci.yml, build.sbt, project/plugins.sbt
Self explanatory. Note that the Scala 2.13.10 github check won't ever finish because we are updating the Scala version, this will be fixed when this PR is merged
=> Update Scala version
